//
// Created by Дональд on 2/9/2022.
//

#ifndef CPPPROGRAMMINGPATHTODATASTRUCTURE_TEST_CLASS_H
#define CPPPROGRAMMINGPATHTODATASTRUCTURE_TEST_CLASS_H


class test_class {

};


#endif //CPPPROGRAMMINGPATHTODATASTRUCTURE_TEST_CLASS_H
